### ISSUE TITLE
any example for docker-compose?

### ISSUE THREAD

**Issue by dony71** [i8beef/HomeAutio.Mqtt.GoogleHome#77]
found docker file here https://hub.docker.com/r/i8beef/homeautio.mqtt.googlehome
but no docker-compose
anybody kindly provide docker-compose.yml ?

**Comment by i8beef** [comment]
Sorry, I don't use docker-compose. Ill leave this open for a bit to see if anyone else has anything to help you.

**Comment by Piedro1** [comment]
I use something like this for rpi:
 
version: '3.3'
services:
    homeautio.mqtt.googlehome:
        restart: always
        container_name: homeautio.mqtt.googlehome
        ports:
            - '5000:5000'
        volumes:
            - '[mountpoint]/config:/app/config'
            - '[mountpoint]/logs:/app/logs'
        environment:
            - VIRTUAL_HOST=[public fqdn]
            - LETSENCRYPT_HOST=[public fqdn]
            - LETSENCRYPT_EMAIL=[mail address]
            - ASPNETCORE_PATHBASE=/google/home
            - TZ=[Local timezone]
        image: 'i8beef/homeautio.mqtt.googlehome:latest-arm32'

**Comment by Vayatoalla** [comment]
My docker-compose includes the reverse proxy. It runs also in a Raspberry.
```
version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 5000:443
    volumes:
      - /home/pi/mydocker/dockercompose-nginx:/etc/nginx
      - /etc/letsencrypt/archive/my.server.com:/etc/ssl/private
    restart: always

  homeautio:
    container_name: homeautio
    hostname: homeautio
    image: i8beef/homeautio.mqtt.googlehome:latest-arm32
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - config:/app/config
      - logs:/app/logs
    restart: always
    environment:
      - ASPNETCORE_PATHBASE=/google/home
      - TZ=Europe/Madrid
volumes:
  config:
  logs:
```
